### ISSUE TITLE
哥们儿，出入凭证那个被和谐了？

### ISSUE THREAD

**Issue by Ricardowdl** [feizao67/GDUF_autocheck_2.0#1]

**Comment by feizao67** [comment]
为方便管理站点，先前的出入凭证已更改站点。
新站点如下：
【出校凭证】
https://gdjrxy.github.io/gduf_io/out.html?studentId=学号&studentName=名字
【入校凭证】
https://gdjrxy.github.io/gduf_io/in.html?studentId=学号&studentName=名字
使用方法与先前一样，为不影响大家的使用，请互相告知！
!!!新增功能!!!
此外该站点新增一项功能
【青年大学习】
https://gdjrxy.github.io/youth_study/index.html
